spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_db
    username: fabricekouonang
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
   # database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: fab
    password: fab
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-Key: 434384848848488484992929292938388383393939939393838839393933333
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activation-account
server:
  port: 8088
